# -*- coding: utf-8 -*-
"""STUDENTS_HABITS_TRACKER.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oSb_q7CqnOA9SiMbAR4CdaA7ruRNA8-h
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# prompt: write a code to create a dataframe and put the data of a file name d'BostonHousing.csv' in it and name it as df

import pandas as pd
df = pd.read_csv('student_habits_performance.csv')
df.head()

df.drop('student_id', axis = 1, inplace = True)

# Get the statistical summary of the data
df.describe()

# Generate a Histogram for all the numerical columns
n_col = df.select_dtypes(include=np.number).columns
n_col

# generate Box plots for the numerical cols
for col in n_col:
    sns.boxplot(df[col])
    plt.xlabel(col)
    plt.ylabel('Frequency')
    plt.title(col)
    plt.show()

# Removing outliers in the columns
for col in n_col:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    df = df[(df[col] >= lower_bound) & (df[col] <= upper_bound)]
    print(f"Outliers removed from {col}")

for col in n_col:
    sns.boxplot(df[col])
    plt.xlabel(col)
    plt.ylabel('Frequency')
    plt.title(col)
    plt.show()

# create a correlation heat map for numerical cols

# create dummmies for gender col
df = pd.get_dummies(df, columns=['gender'], drop_first=True)

df

df.drop('gender_Other', axis = 1, inplace = True)

df['gender_Male'].astype(int)

df.head()

# Encoding gender_Male column
df['gender_Male'] = df['gender_Male'].astype(int)
df.head()

# Encoding Diet Quality
df['diet_quality'].value_counts()

df['diet_quality'] = df['diet_quality'].map({'Poor': 0, 'Good': 1, 'Fair': 2})
df.head()

df['parental_education_level'].value_counts()

df.drop('parental_education_level', axis = 1, inplace = True)

df['part_time_job'].value_counts()

df.drop('part_time_job', axis = 1, inplace = True)

df.head()

df['internet_quality']  = df['internet_quality'].map({'Poor': 0, 'Average': 1, 'Good': 2})
df.head()

df['extracurricular_participation'] = df['extracurricular_participation'].map({'No': 0, 'Yes': 1})
df.head()

# create a heatmap
plt.figure(figsize = (10, 10))
sns.heatmap(df.corr(), annot = True)
plt.show()
plt.tight_layout()

# create a new dataframe based on the highly correlated values
df_new  = df[['study_hours_per_day', 'diet_quality', 'attendance_percentage', 'mental_health_rating','sleep_hours', 'exercise_frequency','exam_score']]
df_new

# Divide data into train and test
from sklearn.model_selection import train_test_split
X = df_new.drop('exam_score', axis = 1)
y = df_new['exam_score']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

# Train the data using linear regression
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train, y_train)

# check score
lr.score(X_train, y_train)

# Check R2 and Adjusted R2 values
from sklearn.metrics import r2_score
y_pred = lr.predict(X_test)
r2 = r2_score(y_test, y_pred)
print("R2 score:", r2)

# Check Adjusted R2 values
n = X_test.shape[0]
p = X_test.shape[1]
adjusted_r2 = 1 - (1 - r2) * (n - 1) / (n - p - 1)
print("Adjusted R2 score:", adjusted_r2)

y_pred = lr.predict(X_test)







"""# Task
Evaluate multiple regression models on the training data and return a dictionary containing their R-squared and Adjusted R-squared scores.

## Import necessary libraries

### Subtask:
Import the required libraries for regression models and evaluation.

**Reasoning**:
Import the necessary libraries for various regression models and evaluation metrics as requested by the subtask.
"""

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.metrics import r2_score
import numpy as np

"""## Define regression models

### Subtask:
Define a dictionary of regression models to be evaluated.

**Reasoning**:
Create a dictionary to store the regression models and instantiate the specified models.
"""

models = {
    'Linear Regression': LinearRegression(),
    'Random Forest Regressor': RandomForestRegressor(n_estimators=100, random_state=42),
    'Support Vector Regressor': SVR()
}

"""## Train and evaluate models

### Subtask:
Iterate through the dictionary of models, train each model on the training data, and evaluate its performance using R-squared and Adjusted R-squared scores.

**Reasoning**:
Iterate through the dictionary of models, train each model, calculate R-squared and Adjusted R-squared, and store the scores in a dictionary.
"""

model_scores = {}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    r2 = r2_score(y_test, y_pred)
    n = X_test.shape[0]
    p = X_test.shape[1]
    adjusted_r2 = 1 - (1 - r2) * (n - 1) / (n - p - 1)
    model_scores[name] = {'R-squared': r2, 'Adjusted R-squared': adjusted_r2}

display(model_scores)

"""## Display results

### Subtask:
Display the dictionary containing the scores of all the regression models.

**Reasoning**:
Display the dictionary containing the scores of all the regression models.
"""

display(model_scores)

"""## Summary:

### Data Analysis Key Findings

*   The `Linear Regression` model achieved the highest R-squared and Adjusted R-squared scores among the evaluated models.
*   The `Random Forest Regressor` performed slightly worse than Linear Regression.
*   The `Support Vector Regressor` had significantly lower R-squared and Adjusted R-squared scores compared to the other models.

### Insights or Next Steps

*   Based on the R-squared and Adjusted R-squared scores, `Linear Regression` appears to be the most suitable model for this dataset.
*   Further analysis could involve exploring hyperparameter tuning for the Random Forest Regressor to potentially improve its performance.

"""